# Generated by Django 3.2.5 on 2021-07-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id especialidad')),
                ('nombre_especialidad', models.CharField(max_length=20, verbose_name='Nombre especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mecanico', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id mecanico')),
                ('nombre_mecanico', models.CharField(max_length=50, verbose_name='Nombre mecanico')),
                ('apellido_mecanico', models.CharField(max_length=50, verbose_name='Apellido mecanico')),
                ('descripcion_mecanico', models.CharField(max_length=240, verbose_name='Descripcion mecanico')),
                ('foto_mecanico', models.ImageField(upload_to='fotosMecanicosDB', verbose_name='Foto mecanico')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad', verbose_name='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('annio', models.IntegerField(verbose_name='Annio')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id_trabajo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id trabajo realizado')),
                ('tipo_trabajo', models.CharField(max_length=50, verbose_name='Tipo de trabajo')),
                ('mas_informacion', models.CharField(max_length=100, verbose_name='Mas informacion')),
                ('foto_trabajo', models.ImageField(upload_to='fotosTrabajosDB')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mecanico', verbose_name='mecanico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo', verbose_name='vehiculo')),
            ],
        ),
    ]
