# Generated by Django 3.2.5 on 2021-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id imagen')),
                ('nombre_imagen', models.CharField(max_length=20, verbose_name='Imagen')),
                ('imagen', models.ImageField(upload_to='imagenesDB')),
            ],
        ),
    ]
