# Generated by Django 3.2.5 on 2021-07-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id servicio')),
                ('nombre_servicio', models.CharField(max_length=20, verbose_name='Nombre servicio')),
                ('descripcion_servicio', models.CharField(max_length=500, verbose_name='Nombre servicio')),
            ],
        ),
    ]
