# Generated by Django 3.2.5 on 2021-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(max_length=50, verbose_name='Nombre servicio'),
        ),
    ]
